# Generated by Django 3.0.5 on 2021-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210427_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
