# Generated by Django 3.0.5 on 2021-05-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210504_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
