# Generated by Django 3.0.5 on 2021-05-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210504_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Choice'),
        ),
    ]
